### ISSUE TITLE
LOLLOL COOKIE GRABBER WHY IS IT OBFUSCATED????/ LOLOLOLOLOL REPORTEDEDEDED

### ISSUE THREAD

**Issue by idkwhattoputhere121** [lucadenhez/robloxnamebot#2]

**Comment by lucadenhez** [comment]
LOLOLOLOL It's literally C# and not obfuscated you eight year old, go actually code something and figure out what a cookie logger does (bruh is this alex?)

lol don't mean to be aggressive or anything but I feel like everyone in 2021 thinks something is a cookie or token logger
