### ISSUE TITLE
lmao tell me is it a cookie grabber or not lmfao pointless attempting to obfuscate it

### ISSUE THREAD

**Issue by idkwhattoputhere121** [lucadenhez/robloxnamebot#4]

**Comment by lucadenhez** [comment]
Well first, it's not obfuscated. This is C# code, look in the .cs file. Second, no it's not a cookie logger. If you knew C# you could read it and see all it does is a GET request to the ROBLOX API, then uses the response to validate the status of the name.

no need to accuse :P

**Comment by idkwhattoputhere121** [comment]
No

**Comment by idkwhattoputhere121** [comment]
Actually i'm looking at the JS file and the C# file is **not** obfuscated.

**Comment by lucadenhez** [comment]
ohhhhhhh I totally forgot I put that is this repo lol. It was to show my friend how an obfuscated cookie logger looks like. Haha I thought you were just trolling
