### ISSUE TITLE
poor kid... you really need to learn because your actions are too sussy... SUS

### ISSUE THREAD

**Issue by idkwhattoputhere121** [lucadenhez/robloxnamebot#7]

**Comment by lucadenhez** [comment]
Found the source again: [https://v3rmillion.net/showthread.php?tid=379922](https://v3rmillion.net/showthread.php?tid=379922)

Happy?

**Comment by lucadenhez** [comment]
Text only version: [https://webcache.googleusercontent.com/search?q=cache:NyCKu4KJr2cJ:https://v3rmillion.net/showthread.php?tid%3D379922&hl=en&gl=us&strip=1&vwsrc=0](https://webcache.googleusercontent.com/search?q=cache:NyCKu4KJr2cJ:https://v3rmillion.net/showthread.php?tid%3D379922&hl=en&gl=us&strip=1&vwsrc=0)
