### ISSUE TITLE
Welp I made a good report on YOU stealing personal info without the users permission. Have fun with your ban!

### ISSUE THREAD

**Issue by idkwhattoputhere121** [lucadenhez/robloxnamebot#8]
Even though im 13 you really make me laugh at you...

**Comment by lucadenhez** [comment]
Even though I provided you with the source of the code, don't own the webhook, and this is a C# repository, I don't really care what you say. Plus I Git cloned all my repos, so yeah. I care about my code, and it seems as if you don't do any, only fork repositories and come after other people for things they didn't do. Have fun being blocked :)
