### ISSUE TITLE
Btw this is the last issue

### ISSUE THREAD

**Issue by idkwhattoputhere121** [lucadenhez/robloxnamebot#9]
If you KNEW it was malicious why did you put it with your files with a discord webhook?
Bro your in highschool and i'm in middle school.
Your a literal joke to me attempting to cookie grab little children looking for rare usernames
smh.

**Comment by lucadenhez** [comment]
😐 You realize that the rare username code is completely unrelated from that JS file?

If you had a brain you could have figured that out.

**Comment by lucadenhez** [comment]
The only two methods in the C# file are:

`static string generateName(int length)
        {
            Random random = new Random();
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_";
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }
        static int makeWebRequest(string name)
        {
            HttpClient request = new HttpClient();
            HttpResponseMessage response = request.GetAsync("https://auth.roblox.com/v1/usernames/validate?request.username=" + name + "&request.birthday=10.20.1999&request.context=Unknown").Result;
            string responseString = response.Content.ReadAsStringAsync().Result;
            dynamic responseJson = JsonConvert.DeserializeObject(responseString);
            return Convert.ToInt32(responseJson.code);
        }`

It does a get request to [https://auth.roblox.com/v1/usernames/validate](https://auth.roblox.com/v1/usernames/validate) with a username and birthday query

Really wish you would have actually read my code.
